apiVersion: v1
kind: Secret
metadata:
  name: api-backend-secret-config
  namespace: dev
type: Opaque
data:
  DB_HOST : MTAuMTI1LjAuNQ==
  DB_DATABASE: cG9zdGdyZXM=
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: cG9zdGdyZXM=
  SPA_CLIENT_ID: MG9hYW1oMmV6dDdIc2RLSnk1ZDc=
