apiVersion: v1

kind: Service

metadata:
  name: node-service
  namespace: stage
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"3000":{"name": "stage-node-service-3000-neg"}}}'
  labels:
    app: node-service
  
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: node-pod
status:
  loadBalancer: {}